
name: jose

repository: https://github.com/appsup-dart/jose


packages:
  - .

ide:
  intellij: false

command:
  version:
    linkToCommits: true
    workspaceChangelog: false

scripts:
  preversion: 
    exec: dart test -j 1